version: "3"
services:
  node:
    build: ./server
  react:
    build: ./client
    depends_on:
      - node
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node
      - react
