version: "3"
services:
  node:
    image: "837437137527.dkr.ecr.us-east-1.amazonaws.com/raspberry-pi:node-latest"
  react:
    image: "837437137527.dkr.ecr.us-east-1.amazonaws.com/raspberry-pi:react-latest"
    depends_on:
      - node
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node
      - react
